[build-system]
requires = [
    "flit_core >=3.2,<4",
    "sphinxcontrib-httpdomain"
]
build-backend = "flit_core.buildapi"

[project]
name = "ruijin"
authors = [{name = "kangkun", email = "graziella@lumache"}]
dynamic = ["version", "description"]
